### PR TITLE
fix: image build logs streaming

### LINKED ISSUE #3083: [Deployments] Real time log streaming isn't working
### Name and Version

[BE]0.16.0-dev.29

### What steps will reproduce the bug?

1. Install image with MCP server name: server `
io.github.oleksii-donets/simple_mcp` and Source type: Source code and stay on Installation log tab

### What is the expected behavior?

Real time log streaming isn't working

Image

### What do you see instead?

Real time log streaming is working

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes epam/ai-dial-admin-frontend#3083 

### Description of changes

  - Wait for each container to have a readable state (running or terminated, checked in both initContainerStatuses and containerStatuses) before attempting to stream its logs; if the pod reaches a terminal phase without the container ever starting, emit a user-visible warning and move on instead of failing the whole job on a log read error.                                                                                                                                                                   
  - Treat SSE client disconnects (AsyncRequestNotUsableException) as normal completion rather than error in ImageBuildLogsService (log + status streams), EventStreamingService, and DeploymentLogsService — log at DEBUG and call emitter.complete() instead of completeWithError(...), removing spurious WARN-level stack traces when users close the stream.
  - Order the new catch before the existing IOException handler (since AsyncRequestNotUsableException extends IOException) so real IO failures still surface as errors.    
  - Add JobRunner unit tests for the two new paths: container never started (skipped with warning) and target container present as a terminated init container (logs still read).

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentLogsService.java [hunk 1]
```diff
@@ -66,6 +67,9 @@ private SafeAutoCloseable startPodStreaming(String id,
                                     emitter.send(SseEmitter.event()
                                             .name("logs")
                                             .data(line));
+                                } catch (AsyncRequestNotUsableException e) {
```
Comment (oleksii-donets) [inline src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentLogsService.java:70]: the new AsyncRequestNotUsableException catch calls emitter.complete() but does not return/break out of the for (var line : batch) loop. The next iteration will call emitter.send(...) on a completed emitter, which will throw again — exactly the WARN-spam pattern this PR is trying to eliminate. Compare with ImageBuildLogsService, which correctly return;s after complete()

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentLogsService.java:70]: Fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by oleksii-donets — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None
