### PR TITLE
fix: perform image definition deletion synchronously

### LINKED ISSUE #160: [Deployments] When I deleted all image versions it's still displayed in the list and when I open it I see 404
### Name and Version

[FE]0.14.0-rc [BE]0.14.0-rc

### What steps will reproduce the bug?

1. Create a few image versions (installed and not) 
2. Deleted All versions
3. Check that it's still displayed in the list
4. Open it

### What is the expected behavior?

When I deleted all image versions it's not displayed in the list

Image

### What do you see instead?

When I deleted all image versions it's still displayed in the list and when I open it I see 404

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #160 

### Description of changes

Refactored image definition deletion process to be synchronous.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by oleksii-donets — COMMENTED** [review]
Good temporary fix for FE consistency, but not ideal long-term.

- It can create long-running transactions and hold locks longer.
- Partial external cleanup + later DB rollback can leave inconsistent state (DB rolled back, but some resources already deleted)
- API response time will increase because delete now blocks until cleanup/cascade finishes, which can hurt UX.


This works as a short-term mitigation. For robust behavior, please prefer “mark as DELETING immediately, hide from reads, cleanup async, hard-delete later.”

File: src/main/java/com/epam/aidial/deployment/manager/cleanup/component/ComponentCleanupService.java [hunk 1]
```diff
@@ -33,6 +35,14 @@ public ComponentCleanupService(List<CleanupStrategy> strategies,
         this.componentRemovalRepository = componentRemovalRepository;
     }
 
+    /**
+     * Returns true if the current thread is performing a synchronous deletion,
+     * so that strategies (e.g. ImageDefinitionCleanupStrategy) can delete child components synchronously.
+     */
+    public boolean isSyncDeletion() {
```
Comment (oleksii-donets) [inline src/main/java/com/epam/aidial/deployment/manager/cleanup/component/ComponentCleanupService.java:42]: isSyncDeletion() leaks orchestration state into strategies via ThreadLocal, which creates more coupling:
- behavior depends on ambient thread state, not explicit input;
- harder to reason about and test;
- brittle for future async/threading changes.
A cleaner design is to pass mode explicitly, e.g. delete(removal, DeletionMode.SYNC|ASYNC) (or separate orchestrators), so strategies don’t query global context. That reduces complexity and keeps control flow obvious.

**Comment by Pasichniuk** [comment]
> Good temporary fix for FE consistency, but not ideal long-term.
> 
> * It can create long-running transactions and hold locks longer.
> * Partial external cleanup + later DB rollback can leave inconsistent state (DB rolled back, but some resources already deleted)
> * API response time will increase because delete now blocks until cleanup/cascade finishes, which can hurt UX.
> 
> This works as a short-term mitigation. For robust behavior, please prefer “mark as DELETING immediately, hide from reads, cleanup async, hard-delete later.”

This PR doesn't have any effect on points 1 and 2. The third one is a requirement - return only after deletion is complete. Proposed solution sound good, but it's unclear if it is worth it at the moment.

File: src/main/java/com/epam/aidial/deployment/manager/cleanup/component/ComponentCleanupService.java (hunk 1 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/deployment/manager/cleanup/component/ComponentCleanupService.java:42]: Adding parameter to 'delete' method looks redundant since only Image Definition strategy needs it. Current implementation is easily extendable

**Review by oleksii-donets — APPROVED** [review]

File: src/main/java/com/epam/aidial/deployment/manager/cleanup/component/ComponentCleanupService.java (hunk 1 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/deployment/manager/cleanup/component/ComponentCleanupService.java:42]: Otherwise, it is complicated to understand the logic where components mutually depend on each other

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>
