### PR TITLE
fix: rolling update is not triggered on args/command modification #85

### LINKED ISSUE #85: [Model Servings] Changes in Configuration section do not trigger redeploy for model with Running status
### Name and Version

[FE]0.13.0-rc [BE]0.13.0-rc

### What steps will reproduce the bug?

1. Go to **Deployments**-> **Model Servings**
2. Find any model with status Running
3. Open the model (Properties tab)
4. Navigate to the **Configuration** section
5. Make any change in:
  • **Arguments** field OR
  • **Command** field
7. Observe available action buttons and model status

### What is the expected behavior?

**Expected Result**
• Any change in the Configuration section (Arguments / Command) for a Running model should:
• trigger redeploy logic
• show **Save & Redeploy** button

### What do you see instead?

**Actual Result**
• Changes in Arguments or Command:
• do not trigger redeploy flow
• do not change model status
• UI shows only **Save** button
• Model remains in **Running** state after saving configuration

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by oleksii-donets**
### Applicable issues

- fixes #85

### Description of changes

- Modify the logic to trigger a rolling update when the args or command fields are changed.

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java [hunk 1]
```diff
@@ -348,19 +349,27 @@ private static boolean isBase64Encoded(String value) {
...
-                && updated instanceof NimDeployment updatedNim) {
-            isGrpcUpdated = !Objects.equals(existingNim.getContainerGrpcPort(), updatedNim.getContainerGrpcPort());
-        }
+        // 1. Check specialized deployment types using pattern matching
+        boolean specializedUpdate = switch (existing) {
+            case NimDeployment exNim when updated instanceof NimDeployment upNim ->
+                    !Objects.equals(exNim.getContainerGrpcPort(), upNim.getContainerGrpcPort());
+
+            case InferenceDeployment exInf when updated instanceof InferenceDeployment upInf ->
+                    !Objects.equals(exInf.getArgs(), upInf.getArgs())
```
Comment (Pasichniuk) [inline src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java:358]: Objects.equals is order-sensitive when comparing lists

Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java:358]: Arguments may be order sensitive, so it is better to keep them this way

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by Pasichniuk — APPROVED** [review]
