### PR TITLE
fix: separate cilium policy update from rolling update

### LINKED ISSUE #112: [Deployments] An internal server error is displayed after adding a new domain and rerunning or adding a new image during reruning
### Name and Version

[FE]0.14.0-rc [BE]0.14.0-rc

### What steps will reproduce the bug?

1. Create container
2. Add the domain and run it
3. Add a new domain and rerun it
4. Rerun the container agai,n and during preparing change the image

Note: also check rerun after: env variables changing and resources changing

### What is the expected behavior?

An internal server error isn't displayed after adding a new domain and rerunning or adding a new image during reruning

### What do you see instead?

An internal server error is displayed after adding a new domain and rerunning or adding a new image during reruning

Image

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Pasichniuk**
### Applicable issues

- fixes #112 

### Description of changes

Separated Cilium Network Policy update from Deployment rolling update. Policy should be updated only if allowedDomains or containerPort changed. Deployment rolling update should not happen if allowedDomains changed.
Additionally, added logic to include NIM gRPC port and default container port to Cilium policy.

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java [hunk 1]
```diff
@@ -623,6 +622,20 @@ private void createCiliumNetworkPolicy(String groupId, List<String> allowedDomai
         log.trace("createCiliumNetworkPolicy. Created Cilium Network Policy: {}", ciliumNetworkPolicy);
     }
 
+    @Override
+    @Transactional(isolation = Isolation.REPEATABLE_READ)
```
Comment (oleksii-donets) [inline src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java]: This method is invoked from a method with the @Transactional annotation, which uses ReadCommitted isolation (the default for PostgreSQL). So here, the effective isolation level is also ReadCommited instead of RepeatableRead

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java [hunk 2]
```diff
@@ -355,8 +360,12 @@ private static boolean isApplicableForRollingUpdate(Deployment existing, Deploym
                 || !Objects.equals(existing.getMinScale(), updated.getMinScale())
                 || !Objects.equals(existing.getMaxScale(), updated.getMaxScale())
                 || !Objects.equals(existing.getResources(), updated.getResources())
-                || !CollectionUtils.isEqualCollection(existing.getAllowedDomains(), updated.getAllowedDomains())
                 || isGrpcUpdated;
     }
 
+    private static boolean isApplicableForCiliumNetworkPolicyUpdate(Deployment existing, Deployment updated) {
+        return !CollectionUtils.isEqualCollection(existing.getAllowedDomains(), updated.getAllowedDomains())
+                || !Objects.equals(existing.getContainerPort(), updated.getContainerPort());
```
Comment (oleksii-donets) [inline src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java:368]: Some deployments may have more than one port, like NIM deployments have containerGrpcPort

Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java:368]: grpc port is not considered when creating Cilium policy, since we focus only on TCP ports.

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java (hunk 1 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java]: Removed isolation parameter

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/test/java/com/epam/aidial/deployment/manager/functional/tests/DeploymentFunctionalTest.java [hunk 3]
```diff
@@ -385,7 +385,51 @@ public void shouldSuccessfullyUpdateDeploymentIfRunningAndImageChanged() {
...
+
+        var updatedDeployment = deploymentService.updateDeployment(savedDeployment.getId(), updateRequest);
+
+        // Then
+        Assertions.assertEquals("updated-deployment", updatedDeployment.getDisplayName());
+        Assertions.assertEquals(savedDeployment.getId(), updatedDeployment.getId());
+        Assertions.assertEquals(allowedDomains, updatedDeployment.getAllowedDomains());
+
+        // should update only once because cilium network policy should be updated and deployment shouldn't
+        verify(resource, times(1)).update();
```
Comment (oleksii-donets) [inline src/test/java/com/epam/aidial/deployment/manager/functional/tests/DeploymentFunctionalTest.java]: With this verification, it is not clear what has been updated. It could be a Knative Service or a Cilium policy.

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java (hunk 2 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java:368]: GRPC may be based on TCP

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java (hunk 2 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/deployment/manager/service/deployment/DeploymentService.java:368]: Added logic to add gRPC port to Cilium Network Policy

File: src/test/java/com/epam/aidial/deployment/manager/functional/tests/DeploymentFunctionalTest.java (hunk 3 above)
Comment (Pasichniuk) [reply src/test/java/com/epam/aidial/deployment/manager/functional/tests/DeploymentFunctionalTest.java]: Refactored this test

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java [hunk 4]
```diff
@@ -656,6 +669,11 @@ private void deleteCiliumNetworkPolicy(String name) {
         }
     }
 
+    protected List<Integer> getCiliumIngressPorts(Deployment deployment) {
```
Comment (oleksii-donets) [inline src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java]: Why not have a getPorts method in the Deployment classes instead?

**Comment by oleksii-donets** [comment]
Another problem is that we do not add default ports to Cilium

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java (hunk 4 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java]: Otherwise, type parameter `D` should be used instead of Deployment

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java (hunk 4 above)
Comment (Pasichniuk) [reply src/main/java/com/epam/aidial/deployment/manager/service/deployment/AbstractDeploymentManager.java]: Not adding a method to Deployment classes to not bring Cilium-related logic to domain layer. Added type parameter usage.

**Comment by Pasichniuk** [comment]
> Another problem is that we do not add default ports to Cilium

Fixed

**Review by oleksii-donets — APPROVED** [review]
