### PR TITLE
fix: set KNative progress-deadline annotation from startup probe config

### LINKED ISSUE #193: Startup probe fails for large models due to KNative progress deadline limit
### Name and Version
ai-dial-admin-deployment-manager-backend [0.14.0]

### Problem

When deploying a large model (e.g. one that takes more than 10 minutes to download), KNative/KServe kills the pod due to the progress deadline limit before the model finishes loading.

The startup probe never gets a chance to succeed because the pod is terminated by KNative's deployment progress deadline before the model is fully downloaded and ready to serve.

### Reference

- [KNative: Configuring progress deadlines](https://knative.dev/docs/serving/configuration/deployment/#configuring-progress-deadlines)

### Expected Behavior

Large models that require extended download/initialization time should be deployable without being killed by the progress deadline.

### PR DESCRIPTION
**Pull request by oleksii-donets**
### Applicable issues

- fixes #193

### Description of changes

KNative has a default `progressDeadline` of 600s (10 min). When deploying large models that need more time to download/initialize, KNative kills the pod before the startup probe can succeed.

This PR auto-derives the `serving.knative.dev/progress-deadline` annotation from the startup probe parameters:

```
progressDeadline = initialDelaySeconds + (periodSeconds × failureThreshold) + 30s buffer
```

**Changes:**
- **`ProgressDeadlineCalculator`** — new utility that computes the deadline from `ProbeProperties`, falling back to Kubernetes defaults for unset fields
- **`KnativeManifestGenerator`** — sets the annotation on the revision template metadata
- **`InferenceManifestGenerator`** — sets the annotation on the InferenceService metadata (KServe propagates it to KNative)
- When no probe is configured, no annotation is set (preserves KNative default of 600s)

### Checklist

- [x] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: src/main/java/com/epam/aidial/deployment/manager/service/manifest/ProgressDeadlineCalculator.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+        if (probe == null || !probe.isEnabled()) {
+            return null;
+        }
+        int initial = probe.getInitialDelaySeconds() != null
+                ? probe.getInitialDelaySeconds() : defaultInitialDelay;
+        int period = probe.getPeriodSeconds() != null
+                ? probe.getPeriodSeconds() : defaultPeriod;
+        int threshold = probe.getFailureThreshold() != null
+                ? probe.getFailureThreshold() : defaultFailureThreshold;
+        int deadline = initial + (period * threshold) + bufferSeconds;
```
Comment (Pasichniuk) [inline src/main/java/com/epam/aidial/deployment/manager/service/manifest/ProgressDeadlineCalculator.java]: Please consider:

The formula 'initialDelaySeconds + (periodSeconds * failureThreshold) + bufferSeconds' is off in two ways:

- Number of periods – periodSeconds is the interval between starts of probes. The 1st probe starts at initialDelaySeconds, the 2nd at initialDelaySeconds + periodSeconds, the 3rd at initialDelaySeconds + 2*periodSeconds, etc. So the failureThreshold-th probe starts after (failureThreshold − 1) periods, not failureThreshold.
- Missing timeout – The last attempt can take up to timeoutSeconds to actually fail (e.g. TCP/HTTP timeout). That time must be added to get the real deadline.

Correct formula (worst-case deadline)
Total time until probe is considered failed (worst case):

initialDelaySeconds + (failureThreshold - 1) * periodSeconds + timeoutSeconds

Meaning:
- initialDelaySeconds – wait after container start before the first probe.
- (failureThreshold - 1) * periodSeconds – time from first probe start to the start of the failureThreshold-th probe (one period between each pair of consecutive probes).
- timeoutSeconds – max duration of the last probe attempt before it’s counted as failed.
Example (e.g. from your test data: initial=5, period=10, timeout=3, failureThreshold=2):

Correct: 5 + (2-1)*10 + 3 = 5 + 10 + 3 = 18 seconds.
Example formula: 5 + 10*2 + <buffer> = 25 seconds (too high and doesn’t include timeout).

File: src/main/java/com/epam/aidial/deployment/manager/service/manifest/ProgressDeadlineCalculator.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    private final int defaultInitialDelay;
+    private final int defaultPeriod;
+    private final int defaultFailureThreshold;
+    private final int bufferSeconds;
+
+    public ProgressDeadlineCalculator(
+            @Value("${app.deployment.progress-deadline.default-initial-delay:0}") int defaultInitialDelay,
+            @Value("${app.deployment.progress-deadline.default-period:10}") int defaultPeriod,
+            @Value("${app.deployment.progress-deadline.default-failure-threshold:3}") int defaultFailureThreshold,
+            @Value("${app.deployment.progress-deadline.buffer-seconds:30}") int bufferSeconds
```
Comment (Pasichniuk) [inline src/main/java/com/epam/aidial/deployment/manager/service/manifest/ProgressDeadlineCalculator.java]: No need for default values here. They are already present in application.yaml

File: src/main/java/com/epam/aidial/deployment/manager/service/manifest/ProgressDeadlineCalculator.java (hunk 1 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/deployment/manager/service/manifest/ProgressDeadlineCalculator.java]: Good catch, fixed in c59cf0b8.

The formula now uses the correct worst-case calculation:
```
initialDelaySeconds + (failureThreshold - 1) * periodSeconds + timeoutSeconds + bufferSeconds
```

- Fixed the off-by-one (`threshold - 1` periods between probes)
- Added `timeoutSeconds` from the probe config (falls back to K8s default of 1s when unset)
- Kept the buffer on top for scheduling delays, image pull time, etc.

File: src/main/java/com/epam/aidial/deployment/manager/service/manifest/ProgressDeadlineCalculator.java (hunk 2 above)
Comment (oleksii-donets) [reply src/main/java/com/epam/aidial/deployment/manager/service/manifest/ProgressDeadlineCalculator.java]: You're right, removed the redundant defaults from `@Value` annotations in c59cf0b8. The defaults in `application.yml` (lines 136-140) are sufficient.

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
The following issues were found:<ul><li>✅ 0 vulnerable package(s)</li><li>✅ 0 package(s) with incompatible licenses</li><li>✅ 0 package(s) with invalid SPDX license definitions</li><li>⚠️ 2 package(s) with unknown licenses.</li></ul>
See the Details below.<h2>License Issues</h2>
<h4><em>settings.gradle</em></h4>
<table><tr><td>Package</td><td>Version</td><td>License</td><td>Issue Type</td></tr><tr><td>com.gradle:common-custom-user-data-gradle-plugin</td><td>2.1</td><td>Null</td><td>Unknown License</td></tr><tr><td>com.gradle:develocity-gradle-plugin</td><td>4.2</td><td>Null</td><td>Unknown License</td></tr></table>
<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td> maven/com.gradle:common-custom-user-data-gradle-plugin </td><td>2.1</td>
      <td> Unknown</td><td>Unknown</td></tr>
<tr><td> maven/com.gradle:develocity-gradle-plugin </td><td>4.2</td>
      <td> Unknown</td><td>Unknown</td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by Pasichniuk — APPROVED** [review]
